table tblDimDate
	lineageTag: e065e753-354b-4871-86f0-e27c50174c4e
	dataCategory: Time

	column DateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: dfc1acf9-1e3d-44dc-9512-1b1637c8aaab
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isUnique
		formatString: M/d/yyyy
		lineageTag: 9fc4b457-aff8-4648-bf5f-deb1db01aca3
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: ef688dd3-b0ae-4d67-8fc7-c4cce1e621a6
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column QuarterLabel
		dataType: string
		lineageTag: 81450504-29be-4d72-baba-d29321c37441
		summarizeBy: none
		sourceColumn: QuarterLabel
		sortByColumn: QuarterNumber

		annotation SummarizationSetBy = Automatic

	column MonthNumber
		dataType: int64
		formatString: 0
		lineageTag: b5e95781-49ee-41f5-9fe8-2778ffb9a682
		summarizeBy: none
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 644663b8-2cf5-47ec-93f4-b775f3f52ad9
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

	column MonthShort
		dataType: string
		lineageTag: ac17aa63-deda-4ba9-99cb-7bc73740c0f2
		summarizeBy: none
		sourceColumn: MonthShort
		sortByColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

	column QuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: ced4acb7-0c0d-4e9c-81af-e6030883444b
		summarizeBy: none
		sourceColumn: QuarterNumber

		annotation SummarizationSetBy = Automatic

	column CalendarQuarter
		dataType: int64
		formatString: 0
		lineageTag: b61c499d-92cf-4d49-8a6e-0d1b95955e3a
		summarizeBy: none
		sourceColumn: CalendarQuarter

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: c7547a44-2b70-4833-9964-ab948e4c733a
		summarizeBy: none
		sourceColumn: DayName

		annotation SummarizationSetBy = Automatic

	column DayShort
		dataType: string
		lineageTag: 128dddf8-3498-4e0f-92ca-66e0e117f8ca
		summarizeBy: none
		sourceColumn: DayShort

		annotation SummarizationSetBy = Automatic

	column WeekNumber
		dataType: int64
		formatString: 0
		lineageTag: f31f78d4-928f-4e73-9155-5b956c2fe324
		summarizeBy: none
		sourceColumn: WeekNumber

		annotation SummarizationSetBy = Automatic

	column DayOfYear
		dataType: int64
		formatString: 0
		lineageTag: bf5c295b-cd14-4b2e-b20f-c2de8eec3c07
		summarizeBy: none
		sourceColumn: DayOfYear

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: 45761ddf-b2c2-437c-adfb-828e2499b653
		summarizeBy: none
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column FiscalMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: 31bae044-ba03-47c0-b321-7d75c246f53c
		summarizeBy: none
		sourceColumn: FiscalMonthNumber

		annotation SummarizationSetBy = Automatic

	column FiscalPeriod
		dataType: string
		lineageTag: 8e97735c-8b10-4ff1-99f9-8e6afcc14a0d
		summarizeBy: none
		sourceColumn: FiscalPeriod

		annotation SummarizationSetBy = Automatic

	column DayType
		dataType: string
		lineageTag: ae3b1d67-99d3-4fd1-bbf6-dcd065c1f630
		summarizeBy: none
		sourceColumn: DayType

		annotation SummarizationSetBy = Automatic

	column IsNewYear
		dataType: string
		lineageTag: 1ee07662-33ac-481a-93d4-18c7a4d47d36
		summarizeBy: none
		sourceColumn: IsNewYear

		annotation SummarizationSetBy = Automatic

	column IsPeakSeason
		dataType: string
		lineageTag: c6e197f8-ec44-485d-b6d2-fc0f1fe7be55
		summarizeBy: none
		sourceColumn: IsPeakSeason

		annotation SummarizationSetBy = Automatic

	partition tblDimDate = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\RetailAnalytics\Sales_Star_Schema.xlsx"), null, true),
				    tblDimDate_Table = Source{[Item="tblDimDate",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(tblDimDate_Table,{{"DateKey", Int64.Type}, {"Date", type date}, {"Year", Int64.Type}, {"QuarterLabel", type text}, {"MonthNumber", Int64.Type}, {"MonthName", type text}, {"MonthShort", type text}, {"QuarterNumber", Int64.Type}, {"CalendarQuarter", Int64.Type}, {"DayName", type text}, {"DayShort", type text}, {"WeekNumber", Int64.Type}, {"DayOfYear", Int64.Type}, {"FiscalYear", Int64.Type}, {"FiscalMonthNumber", Int64.Type}, {"FiscalPeriod", type text}, {"DayType", type text}, {"IsNewYear", type text}, {"IsPeakSeason", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

